### ISSUE TITLE
[C#] Allow for dynamic library loading 

### ISSUE THREAD

**Issue by wkirschenmann** [aneoconsulting/ArmoniK#8]
ArmoniK should allow to dynamically change the library used for a task.
Before executing a task, the worker should check that the proper library (or version of) is loaded before processing the task.

**Comment by wkirschenmann** [comment]
The required library should be indicated within the TaskOption dictionnary during submission with the key "Library".

**Comment by ddubuc** [comment]
fiouuuuuu c'est exactement ce que j'ai fait

J'ai fini je début la



Damien Dubuc
+33 6 73 67 50 33



-------- Message d'origine --------
De : wkirschenmann ***@***.***>
Date : 05/12/2021 14:26 (GMT+01:00)
À : aneoconsulting/armonik ***@***.***>
Cc : Subscribed ***@***.***>
Objet : Re: [aneoconsulting/armonik] [C#] Allow for dynamic library loading (Issue #8)


The required library should be indicated within the TaskOption dictionnary during submission with the key "Library".

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Faneoconsulting%2Farmonik%2Fissues%2F8%23issuecomment-986230221&data=04%7C01%7Cddubuc%40aneo.fr%7C689c369be4284a962e4d08d9b7f2da85%7Ca8b8437b013b4de2b105e96932b6a9c5%7C0%7C0%7C637743075950902321%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=TaEnqqmaiQwLgS1re7VOfzBrMo6zsssx3VE1NiIvk74%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABHZI6IPQ5LDAOREZYPSIQTUPNSAPANCNFSM5JMZA2GA&data=04%7C01%7Cddubuc%40aneo.fr%7C689c369be4284a962e4d08d9b7f2da85%7Ca8b8437b013b4de2b105e96932b6a9c5%7C0%7C0%7C637743075950912277%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=m3D2n1s6ui1FZqTv6gKfW412iXmI3Pq3zdNfuhIfHjU%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cddubuc%40aneo.fr%7C689c369be4284a962e4d08d9b7f2da85%7Ca8b8437b013b4de2b105e96932b6a9c5%7C0%7C0%7C637743075950912277%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=cnCOHhbKQkX2xTDALwmOYezk04zkZBlO7VoaJ12yP3s%3D&reserved=0> or Android<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cddubuc%40aneo.fr%7C689c369be4284a962e4d08d9b7f2da85%7Ca8b8437b013b4de2b105e96932b6a9c5%7C0%7C0%7C637743075950922236%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ENyd5m1Rgz0DXHJwcZxM8TLjnuv%2F%2Bxw4L4%2FNT9BRkCs%3D&reserved=0>.
